# DataSource Config
spring:
  # 此处默认是 h2 的数据库配置
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-h2.sql
    username: root
    password: wo24%$@^uw
    url: jdbc:h2:mem:testdb
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql
  h2:
    # h2 数据库有一个嵌入式的 GUI 控制台，能够让你对数据库的内容进行查询和运行。默认是禁用的，需要通过以下参数进行启用。启用后的地址链接是： http://localhost:8080/h2-console
    console:
      enabled: true
      path: /h2-console
  security:
    user:
      name: user
      # 如果不在此处设置 password，那么在项目启动的时候会默认生成一个 password. e.g: Using generated security password: cb17a51f-3554-482a-8df4-0da2a0f3c6f3
      password: j8w^&k29V^
